interval:
  0.1
total_time:
  100
x:
  start:
    0
  end:
    100
  bias:
    0.
  random:
    0.1
y:
  start:
    0
  end:
    100
  bias:
    0.
  random:
    0.1
z:
  start:
    0
  end:
    100
  bias:
    0.
  random:
    0.1
